# db   d8b   db d888888b d8b   db d8888b.  .d88b.  db   d8b   db .d8888.   
# 88   I8I   88   `88'   888o  88 88  `8D .8P  Y8. 88   I8I   88 88'  YP   
# 88   I8I   88    88    88V8o 88 88   88 88    88 88   I8I   88 `8bo.     
# Y8   I8I   88    88    88 V8o88 88   88 88    88 Y8   I8I   88   `Y8b.   
# `8b d8'8b d8'   .88.   88  V888 88  .8D `8b  d8' `8b d8'8b d8' db   8D   
#  `8b8' `8d8'  Y888888P VP   V8P Y8888D'  `Y88P'   `8b8' `8d8'  `8888Y'   
#                                                                          
#                                                                          
# d8888b.  .d8b.  d8888b. db   dD      .88b  d88.  .d88b.  d8888b. d88888b 
# 88  `8D d8' `8b 88  `8D 88 ,8P'      88'YbdP`88 .8P  Y8. 88  `8D 88'     
# 88   88 88ooo88 88oobY' 88,8P        88  88  88 88    88 88   88 88ooooo 
# 88   88 88~~~88 88`8b   88`8b        88  88  88 88    88 88   88 88~~~~~ 
# 88  .8D 88   88 88 `88. 88 `88.      88  88  88 `8b  d8' 88  .8D 88.     
# Y8888D' YP   YP 88   YD YP   YD      YP  YP  YP  `Y88P'  Y8888D' Y88888P 
#                                                                          
#                                                                          

# Background and foreground colors
background = #181818
foreground = #cccccc


# Standard colors
palette = 0=#181818
palette = 1=#f85149
palette = 2=#2ea043
palette = 3=#bb8009
palette = 4=#0078d4
palette = 5=#c586c0
palette = 6=#4daafc
palette = 7=#cccccc

# Bright colors
palette = 8=#616161
palette = 9=#f85149
palette = 10=#2ea043
palette = 11=#bb8009
palette = 12=#0078d4
palette = 13=#c586c0
palette = 14=#4daafc
palette = 15=#ffffff

#  ______   __       ______                                       
# /_____/\ /_/\     /_____/\                                      
# \:::_ \ \\:\ \    \:::_ \ \                                     
#  \:\ \ \ \\:\ \    \:\ \ \ \                                    
#   \:\ \ \ \\:\ \____\:\ \ \ \                                   
#    \:\_\ \ \\:\/___/\\:\/.:| |                                  
#  ___\_____\/_\_____\/ \____/_/  ______    _______   ______      
# /________/\/_____/\ /_______/\ /_____/\ /_______/\ /_____/\     
# \__.::.__\/\:::_ \ \\::: _  \ \\:::_ \ \\::: _  \ \\:::_ \ \    
#   /_\::\ \  \:\ \ \ \\::(_)  \/_\:\ \ \ \\::(_)  \/_\:\ \ \ \   
#   \:.\::\ \  \:\ \ \ \\::  _  \ \\:\ \ \ \\::  _  \ \\:\ \ \ \  
#    \: \  \ \  \:\_\ \ \\::(_)  \ \\:\_\ \ \\::(_)  \ \\:\_\ \ \ 
#     \_____\/   \_____\/ \_______\/ \_____\/ \_______\/ \_____\/ 
#                                                                 