-- Generated by scripts/hypr2lua.
-- Source: omarchy-windows-dark-mode-theme/hyprland.conf

local activeBorderColor = "rgb(0078d4)"

hl.config({
  general = {
    col = {
      active_border = activeBorderColor,
    },
  },
  group = {
    col = {
      border_active = activeBorderColor,
    },
  },
  animations = {
    enabled = true,
  },
})

hl.curve("myEase", { type = "bezier", points = { { 0.22, 1 }, { 0.36, 1 } } })

hl.animation({
  leaf = "layers",
  enabled = true,
  speed = 6,
  bezier = "myEase",
  style = "slide",
})
hl.animation({
  leaf = "layersIn",
  enabled = true,
  speed = 6,
  bezier = "myEase",
  style = "slide",
})
hl.animation({
  leaf = "layersOut",
  enabled = true,
  speed = 6,
  bezier = "myEase",
  style = "slide",
})

hl.layer_rule({
  no_anim = false,
  match = {
    namespace = "walker",
  },
})
